spring:
  application:
    name: estore
  # Datasource configuration
  datasource:
    name: ecomm
    url: jdbc:h2:mem:ecomm;DB_CLOSE_DELAY=-1;IGNORECASE=TRUE;DATABASE_TO_UPPER=false
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  # H2 configuration
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
  # JPA configuration
  jpa:
    properties:
      hibernate:
        default_schema: ecomm
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    format_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none 
  # Flyway configuration
  flyway:
    url: jdbc:h2:mem:ecomm
    schemas: ecomm
    user: sa
    password: ""